### PR TITLE
prod: add types

### PR DESCRIPTION
**Pull request by Beraliv**
- [ ] need to check if it's working

Connected to [Issue#50](https://github.com/buzinas/simple-scrollbar/issues/50)

### CODE REVIEW

**Comment by Beraliv** [comment]
Two ways:

```ts
declare namespace SimpleScrollBar {
  export function initEl (element: Element): void;
  export function initAll (): void;
  export function moveBar (e: Event): void;
}

export default SimpleScrollBar;
```

or

```ts
export default interface SimpleScrollBar {
  initEl (element: Element): void;
  initAll (): void;
  moveBar (e: Event): void;
}
```

**Comment by Beraliv** [comment]
@buzinas what do you think about adding TS?

**Comment by Beraliv** [comment]
ping @buzinas what do you think?

**Comment by buzinas** [comment]
Thanks for your contribution! Sorry for taking so long to merge this.

**Pull request merged**
