### PR TITLE
RTL direction support

### PR DESCRIPTION
**Pull request by BabkinAleksandr**
Added support for rtl-direction.
Issue #22 
[Demo here](http://sscrollbar-rtl.frontender.pw)

### CODE REVIEW

**Comment by buzinas** [comment]
Can you please resolve the conflicts?

**Comment by BabkinAleksandr** [comment]
Done!

**Comment by BabkinAleksandr** [comment]
@buzinas Sorry, I forgot about demo (attached). But what do you want to see about RTL in readme? You just init scrollbar on rtl or ltr container like before and that's all. Maybe add a little info about rtl support?

**Comment by buzinas** [comment]
> Maybe add a little info about rtl support?

Exactly that :)

**Comment by BabkinAleksandr** [comment]
@buzinas Added info to Readme.
Sorry, if it have some mistakes, my english could be not so well.

**Pull request merged**
